import type { Stage, StageGroupMeta } from "@/types/stage"

export const STAGES: Stage[] = [
  // Group 1: 입력과 기초
  {
    id: 1,
    slug: "immutability",
    title: "불변성 & Immer",
    subtitle: "데이터의 본질",
    concept: "모든 시작은 '새 주소 발급'입니다.",
    difficulty: "easy",
    group: 1,
    groupName: "입력과 기초",
    status: "done",
  },
  {
    id: 2,
    slug: "rendering",
    title: "Rendering & Reconciliation",
    subtitle: "심장 박동 원리",
    concept: "주소가 바뀌면 함수가 재실행되는 '심장 박동' 원리.",
    difficulty: "medium",
    group: 1,
    groupName: "입력과 기초",
    status: "todo",
  },
  {
    id: 3,
    slug: "lifecycle",
    title: "Component Lifecycle",
    subtitle: "컴포넌트의 생애 주기",
    concept: "컴포넌트가 태어나고 죽는 '생애 주기' 이해.",
    difficulty: "easy",
    group: 1,
    groupName: "입력과 기초",
    status: "todo",
  },
  {
    id: 4,
    slug: "hooks-basic",
    title: "Hooks 기초",
    subtitle: "useState & useEffect",
    concept: "상태를 저장하고 변화를 감지하는 '기본 도구'.",
    difficulty: "easy",
    group: 1,
    groupName: "입력과 기초",
    status: "todo",
  },
  {
    id: 5,
    slug: "event-bubbling",
    title: "Event Bubbling & Capture",
    subtitle: "이벤트 전파",
    concept: "브라우저에서 클릭 신호가 어떻게 전달되는지 파악.",
    difficulty: "medium",
    group: 1,
    groupName: "입력과 기초",
    status: "todo",
  },

  // Group 2: 가공과 최적화
  {
    id: 6,
    slug: "hooks-closure",
    title: "Hooks & Closure",
    subtitle: "과거에 갇힌 값",
    concept: "함수가 재실행될 때 '과거의 값'에 갇히는 현상 해결.",
    difficulty: "hard",
    group: 2,
    groupName: "가공과 최적화",
    status: "todo",
  },
  {
    id: 7,
    slug: "memoization",
    title: "Memoization",
    subtitle: "useMemo & useCallback",
    concept: "'주소 안 바뀌면' 예전 계산 결과 재사용하기.",
    difficulty: "medium",
    group: 2,
    groupName: "가공과 최적화",
    status: "todo",
  },
  {
    id: 8,
    slug: "design-systems",
    title: "Design Systems",
    subtitle: "Headless UI",
    concept: "기능(로직)과 디자인을 분리하여 부품화하기.",
    difficulty: "medium",
    group: 2,
    groupName: "가공과 최적화",
    status: "todo",
  },
  {
    id: 9,
    slug: "key-props",
    title: "Key Props & 리스트 렌더링",
    subtitle: "key의 진짜 의미",
    concept: "key={index} 한 줄이 앱을 망가뜨리는 이유.",
    difficulty: "easy",
    group: 2,
    groupName: "가공과 최적화",
    status: "todo",
  },
  {
    id: 10,
    slug: "profiling",
    title: "Performance Profiling",
    subtitle: "수치로 진단",
    concept: "어디서 메모리가 새는지 수치로 진단하는 법.",
    difficulty: "hard",
    group: 2,
    groupName: "가공과 최적화",
    status: "todo",
  },

  // Group 3: 확장과 연결
  {
    id: 11,
    slug: "context",
    title: "Context & Prop Drilling",
    subtitle: "데이터 직통 전달",
    concept: "데이터를 멀리 있는 후손에게 직통으로 쏴주기.",
    difficulty: "medium",
    group: 3,
    groupName: "확장과 연결",
    status: "todo",
  },
  {
    id: 12,
    slug: "state-management",
    title: "State Management",
    subtitle: "Zustand 중앙 금고",
    concept: "복잡한 데이터를 담는 '중앙 금고' 설계.",
    difficulty: "medium",
    group: 3,
    groupName: "확장과 연결",
    status: "todo",
  },
  {
    id: 13,
    slug: "async-state",
    title: "Async State Handling",
    subtitle: "Race Condition",
    concept: "비동기 데이터의 '도착 순서 꼬임' 방지.",
    difficulty: "hard",
    group: 3,
    groupName: "확장과 연결",
    status: "todo",
  },
  {
    id: 14,
    slug: "server-state",
    title: "Server State & Caching",
    subtitle: "TanStack Query",
    concept: "서버 데이터를 메모리에 저장해서 중복 호출 방지.",
    difficulty: "medium",
    group: 3,
    groupName: "확장과 연결",
    status: "todo",
  },
  {
    id: 15,
    slug: "error-boundary",
    title: "Error Boundary",
    subtitle: "에러 방어막",
    concept: "에러 하나로 앱 전체가 죽지 않게 방어막 치기.",
    difficulty: "medium",
    group: 3,
    groupName: "확장과 연결",
    status: "todo",
  },

  // Group 4: 운영과 인프라
  {
    id: 16,
    slug: "testing",
    title: "Testing Strategy",
    subtitle: "Jest & Playwright",
    concept: "내가 짠 로직이 안 깨지게 자동 감시 장치 달기.",
    difficulty: "medium",
    group: 4,
    groupName: "운영과 인프라",
    status: "todo",
  },
  {
    id: 17,
    slug: "hydration",
    title: "Hydration & SSR",
    subtitle: "서버 사이드 렌더링",
    concept: "서버에서 미리 그려서 첫 화면 속도를 0.1초라도 줄이기.",
    difficulty: "hard",
    group: 4,
    groupName: "운영과 인프라",
    status: "todo",
  },
  {
    id: 18,
    slug: "bundle-optimization",
    title: "Bundle Optimization",
    subtitle: "코드 쪼개기",
    concept: "코드를 조각내서 사용자가 필요한 것만 받게 하기.",
    difficulty: "hard",
    group: 4,
    groupName: "운영과 인프라",
    status: "todo",
  },
  {
    id: 19,
    slug: "web-workers",
    title: "Web Workers",
    subtitle: "뒷방 스레드",
    concept: "무거운 계산은 '뒷방 스레드'로 보내서 화면 멈춤 방지.",
    difficulty: "hard",
    group: 4,
    groupName: "운영과 인프라",
    status: "todo",
  },
  {
    id: 20,
    slug: "use-ref-deep",
    title: "useRef 심화",
    subtitle: "렌더 밖의 기억",
    concept: "DOM ref 너머, 렌더 사이에 값을 기억하는 진짜 useRef.",
    difficulty: "medium",
    group: 4,
    groupName: "운영과 인프라",
    status: "todo",
  },
]

export const STAGE_GROUPS: StageGroupMeta[] = [
  { id: 1, name: "입력과 기초", subtitle: "데이터의 본질" },
  { id: 2, name: "가공과 최적화", subtitle: "불필요한 연산 걷어내기" },
  { id: 3, name: "확장과 연결", subtitle: "덩치가 커지는 단계" },
  { id: 4, name: "운영과 인프라", subtitle: "장인의 마무리" },
]

export function getStageBySlug(slug: string): Stage | undefined {
  return STAGES.find((s) => s.slug === slug)
}

export function getStagesByGroup(group: number): Stage[] {
  return STAGES.filter((s) => s.group === group)
}
